on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish to ghcr.io when GHCR_TOKEN secret exists
        if: ${{ env.GHCR_TOKEN != '' }}
        run: echo Publish to ghcr.io using ${{ env.GHCR_TOKEN }}
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
